// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211020165602_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppModel.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Đồng hồ thông minh"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Đồng hồ thời trang"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PC, Máy in"
                        });
                });

            modelBuilder.Entity("AppModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 351, DateTimeKind.Local).AddTicks(6528),
                            Name = "Điện thoại Samsung Galaxy Z Fold3 5G 512GB ",
                            Price = 43990000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/42/248284/Slider/samsung-galaxy-z-fold-3-slider-tong-quan-1020x570.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3448),
                            Name = "Laptop Apple MacBook Air M1 2020 16GB/512GB/7-core GPU",
                            Price = 37490000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/44/243952/apple-macbook-air-m1-2020-z12a00050-1-org.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3480),
                            Name = "Máy tính bảng Huawei MatePad 11",
                            Price = 13490000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/522/241299/huawei-matepad-11-xam-1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3495),
                            Name = "Tai nghe Bluetooth AirPods 2 Apple MV7N2 ",
                            Price = 2990000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/54/236016/bluetooth-airpods-2-apple-mv7n2-imei-1-org.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3508),
                            Name = "Apple Watch S6 40mm viền nhôm dây cao su",
                            Price = 9592000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/7077/229044/apple-watch-s6-40mm-vien-nhom-day-cao-su-hong-cont-1-org.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3524),
                            Name = "Đồng hồ Nữ Esprit ES1L286P0025",
                            Price = 4200000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/7264/250504/esprit-es1l286p0025-nu-1-org.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 10, 20, 23, 56, 2, 352, DateTimeKind.Local).AddTicks(3537),
                            Name = "Máy In laser Trắng Đen Brother HL L2321D",
                            Price = 3490000m,
                            ThumbnailImage = "https://cdn.tgdd.vn/Products/Images/5693/115902/may-in-laser-brother-hl-l2321d-23-600x600.jpg"
                        });
                });

            modelBuilder.Entity("AppModel.Product", b =>
                {
                    b.HasOne("AppModel.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
